mlcommons/GaNDLF

.azure-pipelines/steps.yml
GANDLF/inference_loop.py
GANDLF/training_loop.py
GANDLF/training_manager.py
HISTORY.md
gandlf_run
samples/sample_training.yaml
samples/sample_training_brats.yaml
samples/sample_training_histopathology.yaml
setup.py
testing/test_full.py

Fixes issue #12 
- added option for user to pre-split the training and validation CSVs
- version bump to 0.0.8-dev
- removed version check for unit tests (they should work regardless of any version changes)

Allow pre-split of training and validation data CSVs

---

.gitignore
GANDLF/inference_loop.py
GANDLF/utils.py

Fixes #N.A.
- openslide is imported only when performing histology inference
- makes life **much** simpler for people only interested in radiology

OpenSlide import is disabled if not using histology

---

GANDLF/utils/generic.py
GANDLF/version.py

Fixes #N.A.
- version update for tagging

Version update for tagging

---

GANDLF/compute/training_loop.py
GANDLF/parseConfig.py
GANDLF/utils/__init__.py
GANDLF/utils/imaging.py
GANDLF/utils/parameter_processing.py
HISTORY.md
gandlf_collectStats
gandlf_patchMiner
samples/config_all_options.yaml
setup.py
testing/test_full.py

Fixes #262
- training patches can now be saved by added `save_training: True` in config
- includes #261

Add functionality to save training patches

---

gandlf_patchMiner
setup.py

Fixes #N.A.
- updated API for OPM

Updates to integrate new OPM APIs

---

GANDLF/compute/forward_pass.py
GANDLF/compute/loss_and_metric.py
GANDLF/compute/training_loop.py
GANDLF/metrics/__init__.py
GANDLF/metrics/segmentation.py
HISTORY.md
testing/test_full.py

Fixes #246
- per-label segmentation scores (dice and hausdorff) added

Added option to print per-label segmentation scores

---

GANDLF/data/augmentation/__init__.py
GANDLF/data/augmentation/wrap_torchio.py
GANDLF/parseConfig.py
HISTORY.md
samples/config_all_options.yaml

Fixes #269
- `motion` artifact separated

Motion artifact separated

---

.github/workflows/black.yml

Fixes #285
- automated code linting added

Adding automated linting check for `black`

---

docs/faq.md
docs/usage.md

Fixes #N.A.
- added an faq about where performance metrics are stored
- added usage notes about anonymizer

Updated documentation (faq and usage)

---

GANDLF/post_process/morphology.py
testing/test_full.py

Fixes #N.A.
- hole filling output should be int

Ensure hole filling output is int

---

docs/faq.md
docs/setup.md
gandlf_verifyInstall
setup.py

Fixes #314
- script for installation verification

Added script to verify installation 

---

gandlf_collectStats

Change 
inputDir = os.path.normpath(args.inputDir) to:
inputDir = os.path.normpath(args.modelDir) to match actual args (no inputDir argument)
- Fixes argument parsing to allow for proper usage
- [X ] I have read the [`CONTRIBUTING`](https://github.com/CBICA/GaNDLF/blob/master/CONTRIBUTING.md) guide
- [ X] My PR is based from the [current GaNDLF master ](https://garygregory.wordpress.com/2016/11/10/how-to-catch-up-my-git-fork-to-master/)
- [X ] Non-breaking change (would not break existing functionality): please provide as many details as possible for any breaking change 
- [ X] Function/class source code documentation added/updated

Bug fix in parameters for `gandlf_collectStats`

---

GANDLF/cli/main_run.py
gandlf_run

Fixes #N.A.
- inference mode fixes
- reported by @ujjwalbaid0408

Added some checks for inference mode

---

GANDLF/utils/modelio.py

Fixes #N.A.
- added a key in parameter to ensure the print only happens once

Ensure ONNX-related print only happens once during training

---

setup.py

Fixes #389
- changes the required version of pytorch for macOS

Fixing pytorch version dependency for macOS

---

GANDLF/compute/generic.py

-  Fixes type passed to `get_class_imbalance_weights` (string was passed instead of dataframe)

Fixed type passed to get_class_imbalance_weights

---

GANDLF/data/ImagesFromDataFrame.py
GANDLF/data/preprocessing/__init__.py

Fixes #N.A.
- preprocessing dict extended to include `resize_image` which is same as `resize`

Added a preprocessing dict for `resize_image`

---

GANDLF/compute/forward_pass.py
GANDLF/compute/generic.py

Credit to @sarthakpati for the base implementation!
- Correctly populates header information for inference when only validation CSV is provided to `create_pytorch_objects` function
- Handles a couple other corner cases where training header information is needed
- Used in conjunction with FeTS Challenge 2022
- [ x ] I have read the [`CONTRIBUTING`](https://github.com/CBICA/GaNDLF/blob/master/CONTRIBUTING.md) guide
- [ x ] My PR is based from the [current GaNDLF master ](https://garygregory.wordpress.com/2016/11/10/how-to-catch-up-my-git-fork-to-master/)
- [ x ] Non-breaking change (would not break existing functionality): please provide as many details as possible for any breaking change

Create pytorch objects inference fix

---

GANDLF/compute/forward_pass.py
GANDLF/compute/inference_loop.py
GANDLF/data/post_process/tensor.py
testing/test_full.py

Fixes #431
- if jpg is detected, cast to 8-bit
- ensure tensor output from post-processing module

Supporting JPG for writing segmentation output

---

GANDLF/compute/inference_loop.py
HISTORY.md

Fixes #464
- blending option added with default alpha of 0.5 with option to specify in config with the option `blending_alpha`
- added a new colormap `agni` that is pure red and black for easier visualization
- includes #458

Added blending probability maps with original WSI

---

GANDLF/models/imagenet_vgg.py

Fixes #N.A.
- added option to using not pretrained weights for the imagenet vgg models

Added option to not pick up pretrained weights for `imagenet_vgg`

---

GANDLF/data/post_process/morphology.py
GANDLF/utils/__init__.py
GANDLF/utils/generic.py
GANDLF/utils/tensor.py
docs/extending.md
testing/test_full.py

Fixes #N.A.
- added a helper function to return numpy array from `torch.Tensor` or `sitk.Image`
- reduces amount of code

Single utility function to return array from tensor/image

---

.github/workflows/python-test.yml

Fixes #516 
- Changes the CI workflow file python-test.yml to skip testing / coverage report steps instead of skipping the entire build job. This will allow branch protection to still work with docs-only PRs

Change python-test.yml to pass on docs-only

---

GANDLF/compute/inference_loop.py
GANDLF/compute/training_loop.py
GANDLF/utils/__init__.py
GANDLF/utils/modelio.py
HISTORY.md
testing/test_full.py

Fixes #538
- added new saved models `initial` and `latest` in addition to `best` to improve model debugging
- added preference order for inference: `best` followed by `latest`

Added ability to save `initial` and `latest` models in addition to `best`

---

GANDLF/cli/main_run.py
GANDLF/losses/regression.py
testing/test_full.py

Fixes #800 
- Fix some code issues based on codacy.  https://app.codacy.com/gh/mlcommons/GaNDLF/issues/current?levels=Warning&categories=CodeStyle

Fix code issues reported by codacy

---

.github/workflows/codacy.yml
.github/workflows/codeql-analysis.yml
.github/workflows/devcontainer.yml
.github/workflows/docker-image.yml
.github/workflows/mlcube-test.yml
.github/workflows/openfl-test.yml
.github/workflows/ossar-analysis.yml
.github/workflows/python-test.yml

- ensure tests are triggered for pull requests initiated to all branches

Trigger tests for pull requests to all branches

---

.devcontainer/onCreateCommand.sh
.devcontainer/postCreateCommand.sh
.github/workflows/mlcube-test.yml
.github/workflows/openfl-test.yml
.github/workflows/python-test.yml
Dockerfile-CPU
Dockerfile-CUDA11.8
Dockerfile-CUDA12.1
Dockerfile-ROCm
docs/setup.md
setup.py

Fixes #856
- updated pytorch and torchio versions in setup
- made analogoes updates for docker files
- updated relevant documentation

Update PyTorch dependency

---

GANDLF/entrypoints/optimize_model.py
GANDLF/entrypoints/patch_miner.py
GANDLF/entrypoints/preprocess.py
testing/entrypoints/test_patch_miner.py
testing/entrypoints/test_preprocess.py

Fixes #849, #851
- updated cli options for the new cli

Updated CLI options for new API

---

GANDLF/data/augmentation/__init__.py
setup.py

- Right now `setup.py` places some GANDLF repo files to `site-packages/` of the user's python env. This cleaning helps to keep all gandlf files in `site-packages/GANDLF` so keeping user env tidy + removes other unused parts of `setup.py`
- Fix for #889

Cleaning setup

---

GANDLF/cli/generate_metrics.py
GANDLF/entrypoints/generate_metrics.py
testing/entrypoints/test_generate_metrics.py
testing/test_full.py

Fixes #N.A.
- input csv can now be split into target and prediction csvs
- multiple sanity checks to ensure coherence

Metrics library updated to support comma separate inputs

---

GANDLF/cli/post_training_model_optimization.py
GANDLF/entrypoints/optimize_model.py
GANDLF/utils/modelio.py
testing/entrypoints/test_optimize_model.py
testing/test_full.py

Fixes #895
- added a separate cli parameter
- internal logic updated to handle new parameter

Added output path for optimize model 

---

GANDLF/compute/forward_pass.py
GANDLF/compute/loss_and_metric.py
GANDLF/compute/step.py
GANDLF/compute/training_loop.py
GANDLF/data/__init__.py
GANDLF/logger.py
GANDLF/metrics/__init__.py
GANDLF/metrics/classification.py
GANDLF/metrics/regression.py
GANDLF/utils/generic.py
GANDLF/utils/tensor.py

Fixes: N.A.
- The PR addresses a few important bugs in how metrics are calculated. 
- Because of how the batches are structured, during multi-batch training, only the first batch was used to calculate metrics. 
- The current codebase is fine with batch size of 1.
- This has no effect on validation/testing/inference runs.

Fix train metrics

---

GANDLF/compute/forward_pass.py
GANDLF/entrypoints/anonymizer.py
GANDLF/entrypoints/cli_tool.py
GANDLF/entrypoints/collect_stats.py
GANDLF/entrypoints/config_generator.py
GANDLF/entrypoints/construct_csv.py
GANDLF/entrypoints/debug_info.py
GANDLF/entrypoints/deploy.py
GANDLF/entrypoints/generate_metrics.py
GANDLF/entrypoints/optimize_model.py
GANDLF/entrypoints/patch_miner.py
GANDLF/entrypoints/preprocess.py
GANDLF/entrypoints/recover_config.py
GANDLF/entrypoints/run.py
GANDLF/entrypoints/split_csv.py
GANDLF/entrypoints/verify_install.py
GANDLF/logging_config.yaml
GANDLF/utils/__init__.py
GANDLF/utils/gandlf_logger.py
GANDLF/utils/gandlf_logging.py
MANIFEST.in
docs/extending.md
setup.py
testing/test_full.py

Fixes #755 
This PR fixes the issues from [this PR](https://github.com/mlcommons/GaNDLF/pull/881#issue-2333481102)
I have tried to implement this [ref](https://github.com/mlcommons/GaNDLF/pull/881#discussion_r1661348706)
I  have **NOT** implemented the tqdm [ref](https://github.com/mlcommons/GaNDLF/pull/881#issuecomment-2152197420). I will create a separate PR. 
This screenshot shows how logging messages are in the file. 
-

Add logging final version

---

GANDLF/metrics/classification.py

For binary classification, AUROC metric requires a proba just of the class 1, with shape of `(N,)` rather then `(N,C)` as for multiclass.
https://lightning.ai/docs/torchmetrics/stable/classification/auroc.html#binaryauroc
So, right now binary classification AUROCmetric should fail (at least, it always fails for me). We may check why CI tests work as expected btw...
- ~[ ] Function/class source code documentation added/updated (ensure `typing` is used to provide type hints, including and not limited to using `Optional` if a variable has a pre-defined value).~
- ~[ ] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).~
- ~[ ] If adding a git submodule, add to list of exceptions for black styling in …

Fix binary auroc error

---

samples/config_classification.yaml

- the sample configuration for classification did not have the `class_list`, which is needed.

Update sample configuration for classification

---

docs/getting_started.md
docs/index.md
docs/usage.md

-  The changes are only on the documentation. Added an early explanation of config files and emphasized GaNDLF's purpose, plus added some edits further on for clarity and flow and to attract user's eye to the most important information.

Updated GaNDLF documentation for clarity

---

.github/PULL_REQUEST_TEMPLATE.md
GANDLF/entrypoints/anonymizer.py
GANDLF/entrypoints/cli_tool.py
GANDLF/entrypoints/collect_stats.py
GANDLF/entrypoints/config_generator.py
GANDLF/entrypoints/construct_csv.py
GANDLF/entrypoints/debug_info.py
GANDLF/entrypoints/deploy.py
GANDLF/entrypoints/generate_metrics.py
GANDLF/entrypoints/optimize_model.py
GANDLF/entrypoints/patch_miner.py
GANDLF/entrypoints/preprocess.py
GANDLF/entrypoints/recover_config.py
GANDLF/entrypoints/run.py
GANDLF/entrypoints/split_csv.py
GANDLF/entrypoints/verify_install.py
GANDLF/utils/gandlf_logging.py
docs/extending.md

- Update the cli commands, adding `--log-file` parameter. 
- Update the docs.extending
If the user doesn't use the --log-file par, the logs will be saved in the `/tmp/.gandlf` dir
If the user uses the `--log-file` parameter.

Add log file parameter to cli commands

---

.github/workflows/openfl-test.yml

Resolves Github Actions change to FQDN
- Adds environment variable to OpenFL Github Actions test to resolve FQDN to localhost instead of >64 length FQDN they have migrated to
- [] Function/class source code documentation added/updated (ensure `typing` is used to provide type hints, including and not limited to using `Optional` if a variable has a pre-defined value).

Fix spurious errors in OpenFL Github Actions workflow

---

GANDLF/utils/gandlf_logging.py

Fixes #913 
-  Updated gandlf_logging to flush the assert logs into the file using the  [sys.excepthook](https://docs.python.org/3/library/sys.html#sys.excepthook)

Assert messages to flush to the log file

---

.github/workflows/python-test.yml
README.md

Added the option to upload coverage to codacy

---

GANDLF/version.py
docs/migration_guide.md
samples/config_all_options.yaml
samples/config_classification.yaml
samples/config_getting_started_classification_histo2d.yaml
samples/config_getting_started_classification_rad3d.yaml
samples/config_getting_started_regression_histo2d.yaml
samples/config_getting_started_regression_rad3d.yaml
samples/config_getting_started_segmentation_histo2d.yaml
samples/config_getting_started_segmentation_rad3d.yaml
samples/config_regression.yaml
samples/config_segmentation_brats.yaml
samples/config_segmentation_histology.yaml
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml
tutorials/classification_medmnist_notebook/config.yaml

Version updated for development

---

.github/workflows/black.yml
GANDLF/compute/inference_loop.py
GANDLF/compute/training_loop.py
GANDLF/config_manager.py
GANDLF/logger.py
GANDLF/models/imagenet_unet.py
GANDLF/privacy/opacus/__init__.py
GANDLF/privacy/opacus/config_parsing.py
GANDLF/privacy/opacus/model_handling.py
GANDLF/privacy/opacus/training_utils.py
setup.py
testing/test_full.py

Fixes #944 
- Add DP-enabled training and inference from private repo
- Most of the code is copy-paste from the private repo, with some added documentation and changes from raised errors to assertions.

Added functionality related to DP training

---

docs/customize.md

Fixes #951
- documentation on how someone can train private models has been added

Added documentation on private model training

---

GANDLF/models/dynunet_wrapper.py
testing/test_full.py

Fixes #949 
- Calculate automatically the kernel and strides for dynunet model
- Update the tests

Automatic set strides kernels in dynunet

---

docs/usage.md

Fixes #962
-  Add documentation about --log-file parameter

Add documentation about the log file parameter

---

GANDLF/version.py
samples/config_all_options.yaml
samples/config_classification.yaml
samples/config_getting_started_classification_histo2d.yaml
samples/config_getting_started_classification_rad3d.yaml
samples/config_getting_started_regression_histo2d.yaml
samples/config_getting_started_regression_rad3d.yaml
samples/config_getting_started_segmentation_histo2d.yaml
samples/config_getting_started_segmentation_rad3d.yaml
samples/config_regression.yaml
samples/config_segmentation_brats.yaml
samples/config_segmentation_histology.yaml
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml
tutorials/classification_medmnist_notebook/config.yaml

Fixes #N.A.
- version updated without `-dev` for release

Version updated for release

---

GANDLF/compute/loss_and_metric.py

Fixes #
- minor spelling correction in the comment 
- [ X] Non-breaking change (does **not** break existing functionality): provide **as many** details as possible for _any_ breaking change.
- [ X] Function/class source code documentation added/updated (ensure `typing` is used to provide type hints, including and not limited to using `Optional` if a variable has a pre-defined value).
- [ X] Code has been [blacked](https://github.com/psf/black#usage) for style consistency and linting.
- [X ] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).
- [ X] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/mlcommons/GaNDLF/blob/master/pyproject.toml) …

Correct spelling error

---

testing/test_full.py

Fixes #1007
- added a check to ensure that only segmentation-based dataset get pulled in for csv creation

Fix for new unit test data

---

GANDLF/cli/generate_metrics.py
GANDLF/metrics/segmentation_panoptica.py
docs/usage.md
samples/config_segmentation_metrics_brats_concise.yaml
samples/config_segmentation_metrics_brats_default.yaml

Fixes #1013
- added a new config to pass panoptica parameters
- added associated docs

Added ability to customize segmentation

---

GANDLF/metrics/segmentation_panoptica.py
GANDLF/version.py
samples/config_all_options.yaml
samples/config_classification.yaml
samples/config_getting_started_classification_histo2d.yaml
samples/config_getting_started_classification_rad3d.yaml
samples/config_getting_started_regression_histo2d.yaml
samples/config_getting_started_regression_rad3d.yaml
samples/config_getting_started_segmentation_histo2d.yaml
samples/config_regression.yaml
samples/config_segmentation_brats.yaml
samples/config_segmentation_histology.yaml
samples/config_segmentation_metrics_brats_default.yaml
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml

Fixes #N.A.
- updated version for release
- not to be merged in until other BraTS sample configs are merged
- disable citation message from panoptica

Updated version for release
