.gitignore
setup.py

Fixes issue #N.A.
- setup updated to ensure Windows installation works correctly

Updated installation for Windows

---

docs/_config.yaml

Fixes issue #(Enter issue number here)
- persistent TOC for documentation site

updated config for persistent TOC on left

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
GANDLF/utils.py
SECURITY.md
docs/extending.md
docs/usage.md
samples/sample_training.yaml
samples/sample_training_brats.yaml
samples/sample_training_histopathology.yaml

Fixes issue #N.A.
- Links updated in code and documentation

Documentation and link updates 

---

GANDLF/training_loop.py
testing/data.zip
testing/test_full.py

Fixes issue #N.A.
- Minor fixes to ensure pytest works

PyTest fixes

---

GANDLF/data/ImagesFromDataFrame.py
GANDLF/training_manager.py

Fixes issue #NA
- a print added to make it clear to user when a previous parameter is picked up
- anisotropic syntax fix

added a message stating previous parameters have been picked

---

GANDLF/data/ImagesFromDataFrame.py
GANDLF/inference_loop.py
GANDLF/training_loop.py
GANDLF/training_manager.py

Fixes issue #NA
- syntax fix for n_channels

Inference loop fix when n_channels are absent

---

docs/extending.md
docs/setup.md

Fixes #6
- installation instructions updated

Installation instructions updated

---

GANDLF/parameterParsing.py
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml
testing/test_full.py

Fixes #26
- metrics added in config for clarity
- https://github.com/CBICA/GaNDLF/issues/27#issuecomment-808228330
- pre-trained imagenet models added

Refactor: testing configs updated with metrics

---

.github/ISSUE_TEMPLATE/---bug-report.md
CONTRIBUTING.md
GANDLF/models/MSDNet.py
GANDLF/parameterParsing.py
GANDLF/parseConfig.py
GANDLF/preprocessing.py
HISTORY.md
docs/README.md
docs/extending.md
docs/index.md
docs/usage.md
samples/config_all_options.yaml
samples/config_classification.yaml
samples/config_regression.yaml
samples/config_segmentation_brats.yaml
testing/test_full.py

Fixes #(issue_number)
- `psize` changed to 'patch_size'
- text updated from "GANDLF" to "GaNDLF"
- MSDNet fixed
- documentation updates
- configs updated with metrics

Refactor: psize changed to patch_size and other minor fixes

---

GANDLF/training_loop.py
GANDLF/utils.py

Fixes #32
- the logic from master has been imported into refactor

Refactor: regression/classification model output fix

---

GANDLF/logger.py
GANDLF/losses.py
GANDLF/metrics.py
GANDLF/parseConfig.py
GANDLF/training_loop.py
GANDLF/utils.py

Fixes #N.A.
- memory fix
- some prints removed

Refactor: memory fix for loss/metrics

---

GANDLF/data/ImagesFromDataFrame.py
GANDLF/preprocessing.py
samples/config_all_options.yaml

Fixes #N.A.
- non-zero normalization fixed

Fixing normalization

---

GANDLF/__init__.py

Fixes #N.A.
- added version information

added version info

---

GANDLF/training_loop.py
setup.py

Fixes #N.A.
- minor error check added
- version update for tagging
- final tag before refactor

Error check added

---

GANDLF/inference_loop.py
GANDLF/utils.py
gandlf_run

Fixes #N.A.
- fixes the inference pipeline for rad

Inference fixes

---

GANDLF/utils.py

Fixes #(issue_number)
- csv construction improved

better logic to remove unwanted subjects

---

GANDLF/__init__.py
GANDLF/data/ImagesFromDataFrame.py
GANDLF/inference_loop.py
GANDLF/preprocessing.py
GANDLF/utils.py
HISTORY.md
docs/extending.md
docs/setup.md
gandlf_run
samples/config_all_options.yaml
samples/config_classification.yaml
samples/config_regression.yaml
samples/config_segmentation_brats.yaml
samples/config_segmentation_histology.yaml
setup.py
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml

Fixes #N.A.
- sync up with master

Sync with master

---

GANDLF/models/densenet.py
GANDLF/models/vgg.py

Fixes #N.A.
- dims error check added

added error check for dims

---

GANDLF/data/ImagesFromDataFrame.py

Fixes #N.A.
- Persistent resize check has been added
- no algorithmic change

Persistent resize check

---

GANDLF/training_loop.py
docs/usage.md
setup.py

Fixes #5
- Integrated M3D-CAM into the validation loop of training_loop.py

M3D-CAM integration for training/validation

---

GANDLF/data/ImagesFromDataFrame.py
GANDLF/parameterParsing.py
GANDLF/training_loop.py
GANDLF/utils.py
setup.py

Fixes #N.A.
- weighted loss calculation is now re-enabled
- numpy version is now fixed for consistency
- default control points for elastic updated

Weighted loss re-enabled

---

GANDLF/data/ImagesFromDataFrame.py
GANDLF/losses.py
GANDLF/parseConfig.py
GANDLF/training_loop.py
samples/config_all_options.yaml

Fixes #57
- padding is now done by reading the parameter `enable_padding` from the config file
- initialization of `ImagesFromDataFrame` has been simplified
- includes #56

Padding enabled via config

---

GANDLF/losses.py

Fixes #NA
- DCCE is now working

DCCE is now working

---

GANDLF/parseConfig.py

Fixes #N.A.
- improving channel initialization for older config files

Channel initialization has been improved

---

GANDLF/training_loop.py
GANDLF/training_manager.py
HISTORY.md

Fixes #60 
- inconsistency in console and log is now fixed

Fixing #60

---

GANDLF/inference_loop.py
GANDLF/inference_manager.py
GANDLF/training_loop.py
GANDLF/utils.py
gandlf_run
setup.py
testing/test_full.py

Fixes #N.A.
- inference fixes for rad
- redundant variables removed
- headers are now getting included in parameters from the beginning

Refactor: inference fixes

---

GANDLF/inference_loop.py
GANDLF/inference_manager.py
GANDLF/training_loop.py
GANDLF/training_manager.py
gandlf_run
testing/test_full.py

Fixes #63 
- inference unit test added
- function requirements are now consolidated, and we no longer require `headers` as a separate variable

Inference unit test added

---

GANDLF/training_loop.py

Fixes #N.A.
- always save the first model

Ensuring a single model is always saved

---

GANDLF/utils.py

Fixes #53
- minimum patch size added for unets

Added minimum patch size check for unets

---

docs/usage.md

minor doc updates

---

GANDLF/inference_loop.py
GANDLF/parseConfig.py

Fixes #N.A.
- generic compute location for histo compute
- defaults added in `parseConfig`

Refactor: minor code cleanup

---

.azure-pipelines/steps.yml
azure-pipelines.yml

Fixes #N.A.
- enabled unit testing for PR

trying the tests

---

GANDLF/training_loop.py

Fixes #N.A.
- tqdm added for dataloader iteration
- added hostname for debugging

tqdm added for dataloader iteration

---

GANDLF/misc_utils/adaptive_gradient_clipping.py
GANDLF/misc_utils/clip_gradients.py
GANDLF/misc_utils/grad_scaler.py
GANDLF/preprocessing.py
GANDLF/training_loop.py
gandlf_run
samples/config_all_options.yaml
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml

Fixes #50 
- This adds gradient clipping by normalizing gradients by norm, by value and adaptive gradient clipping.

added base_files for clip grad

---

.github/workflows/codeql-analysis.yml
README.md

Fixes #88
- automatic code analysis added

Adding automated code analysis via CodeQL

---

testing/test_full.py

testing now covers grad_clip testing

---

GANDLF/misc_utils/grad_scaler.py
GANDLF/preprocessing.py
GANDLF/training_loop.py
HISTORY.md

Fixes #90
- added epoch information to `output_predictions.csv`
- some blacking of files

90 epoch info

---

GANDLF/models/vgg.py
GANDLF/parseConfig.py
GANDLF/training_loop.py
GANDLF/utils.py

Fixes #N.A.
- VGG is now generalizing a bit better
- `clip_mode` eval fix
- `output_predictions` is now getting appended properly

VGG and minor syntax fixes

---

GANDLF/logger.py
GANDLF/training_loop.py
GANDLF/training_manager.py

Fixes #N.A.
- made file names clearer (the format is now `$purpose_$type` rather than `$type_$purpose` to make things clearer during navigation)
- `training_loop` cli has been added for farming the training across multiple jobs

Filenames are now clearer

---

GANDLF/models/modelBase.py
GANDLF/parseConfig.py
GANDLF/training_loop.py
GANDLF/training_manager.py
HISTORY.md
testing/test_full.py

Fixes #98
- adding memory tracking for RAM and CUDA
- includes #97

98 memory usage logs

---

GANDLF/models/modelBase.py

Fixes #N.A.
- single place for dimension check

single place to check dimensions

---

GANDLF/data/ImagesFromDataFrame.py
GANDLF/models/modelBase.py
GANDLF/parseConfig.py
GANDLF/training_loop.py
GANDLF/training_manager.py
HISTORY.md
testing/test_full.py

Fixes #100
- rgb image reading fixed
- includes #99

100 rgb fix

---

GANDLF/parseConfig.py

Fixes #N.A.
- `clip_mode` default updated to ensure it gets parsed as `str`

`clip_mode` default updated

---

GANDLF/losses.py
GANDLF/training_loop.py
docs/usage.md
samples/config_all_options.yaml
samples/config_classification.yaml
samples/config_regression.yaml
samples/config_segmentation_brats.yaml
samples/config_segmentation_histology.yaml

Fixes #105 
- multi-batch training fixed
- documentation and config fixes from @bahetibhakti

105 multi batch fix

---

docs/extending.md
docs/setup.md

Minor changes in documentation

---

GANDLF/parseConfig.py

Fixes #N.A.
- bugfix for 'accuracy' metric

Minor bugfix for accuracy

---

.github/workflows/python-test.yml

rename workflow for clarity

---

docs/setup.md

Updated installation instructions for Windows

---

GANDLF/data/ImagesFromDataFrame.py
GANDLF/metrics.py
GANDLF/training_loop.py
docs/usage.md
samples/config_all_options.yaml
samples/sample_test.csv

Fixes #115
- added per-subject consistency checking
- tqdm messages added
- documentation updated to fix #115
- see https://github.com/fepegar/torchio/discussions/587

Added per-subject consistency checking 

---

GANDLF/losses.py
GANDLF/parseConfig.py
testing/test_full.py

Fixes #120 
- added unit tests
- simplified implementation of various CE losses

Added a generic `CE_loss` to simplify implementation and unit tests

---

samples/config_all_options.yaml
samples/config_classification.yaml
samples/config_regression.yaml
samples/config_segmentation_brats.yaml
samples/config_segmentation_histology.yaml
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml

Fixes #N.A.
- config version updated

version update in configurations

---

GANDLF/data/ImagesFromDataFrame.py
GANDLF/utils.py

Fixes #128 
- memory usage for consistency check fixed

128 consistency fix

---

GANDLF/data/ImagesFromDataFrame.py
GANDLF/inference_dataloader_histopath.py
GANDLF/inference_loop.py
GANDLF/models/seg_modules/DownsamplingModule.py
GANDLF/models/seg_modules/FCNUpsamplingModule.py
GANDLF/models/seg_modules/IncDropout.py
GANDLF/models/seg_modules/ResNetModule.py
GANDLF/models/seg_modules/add_conv_block.py
GANDLF/parameterParsing.py
GANDLF/preprocessing.py
gandlf_run
testing/test_full.py

Fixes #125 
- fixing some basic codacy issues
- added a test for `brain_age` model
- added tests for preprocessing functions

Fixing some codacy issues

---

GANDLF/data/ImagesFromDataFrame.py
GANDLF/losses.py
GANDLF/training_loop.py
testing/test_full.py

Fixes #N.A.
- Adding a few new tests

Some more tests added

---

GANDLF/utils.py
GANDLF/version.py
testing/config_classification.yaml

Fixes #134
- regression bugfix
- version updated for tagging

simple bugfix for #134

---

GANDLF/version.py
HISTORY.md
samples/config_all_options.yaml
samples/config_classification.yaml
samples/config_regression.yaml
samples/config_segmentation_brats.yaml
samples/config_segmentation_histology.yaml
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml

Fixes #N.A.
- version updates throughout for development

Version updated for development

---

samples/DFUC21 best config/config_classification_vgg11_without_preprocess.yaml

DFUC21 Config File added.

---

GANDLF/models/seg_modules/DecodingModule.py
GANDLF/models/seg_modules/EncodingModule.py
GANDLF/models/seg_modules/IncDropout.py
GANDLF/models/seg_modules/IncUpsamplingModule.py
GANDLF/models/seg_modules/InceptionModule.py
GANDLF/models/seg_modules/ResNetModule.py
GANDLF/models/seg_modules/out_conv.py
GANDLF/models/unet.py
MANIFEST.in
testing/test_full.py

Fixes #142
- residual connections are now working as expected
- variable naming consistency
- includes #140

UNet residual connections fixed

---

MANIFEST.in

Fixes #N.A.
- a [`MANIFEST.in` file](https://packaging.python.org/guides/using-manifest-in/) helps in packaging

Added a manifest file for better package management

---

GANDLF/models/fcn.py
GANDLF/models/unet.py
MANIFEST.in

Fixes #N.A.
- comment changed
- updated conda badge (#144 included)

Minor comment change

---

README.md

Fixes #N.A.
- better conda badge

updated conda badge

---

docs/extending.md
docs/setup.md

Minor doc update

---

GANDLF/utils.py

Fixes #147
- when no label is present, we should not be trying to compare `'label'`

Fixing situation where no label is present

---

GANDLF/parameterParsing.py

Densenet no longer requires patches to be divisible by 16

---

GANDLF/losses.py
GANDLF/metrics.py
GANDLF/parameterParsing.py
GANDLF/training_loop.py
GANDLF/utils.py
MANIFEST.in
testing/config_classification.yaml
testing/config_segmentation.yaml
testing/test_full.py

Fixes #141
- Added weighted cross entropy loss to losses.py

Weighted Cross Entropy Implementation

---

GANDLF/losses.py

Device fix for CEL

---

GANDLF/models/sdnet.py
GANDLF/parameterParsing.py

Codacy fixes

---

gandlf_run

bool type fix

---

GANDLF/losses.py
GANDLF/parameterParsing.py
gandlf_run

156 classification fix

---

GANDLF/metrics.py
setup.py
testing/config_classification.yaml

New metric added.
-  F1 metric implemented.

F1 metric implemented.

---

GANDLF/data/ImagesFromDataFrame.py
HISTORY.md
MANIFEST.in
samples/config_all_options.yaml
setup.py
testing/test_full.py

Fixes #160
- all images can now be reoriented to a single orientation during preprocessing

Added option of `to_canonical`

---

GANDLF/metrics.py
GANDLF/training_loop.py

Fixes #166 
- spacing is now getting picked up correctly

Syntax fixes for spacing

---

GANDLF/metrics.py
GANDLF/training_loop.py

Fixes #N.A.
- Minor cout removed
- Bug fix for multi-label metric calculation
- Blacking code

Minor cout fix and blacking code

---

GANDLF/inference_manager.py

Fixes #172 
- One liner which correctly checks if the logits file existsç
- [] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/CBICA/GaNDLF/blob/master/GANDLF/version.py)
- [] If adding a submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/CBICA/GaNDLF/blob/master/pyproject.toml) file 
- [] [Usage documentation](https://github.com/CBICA/GaNDLF/blob/master/docs) has been updated, if appropriate
- [] [History](https://github.com/CBICA/GaNDLF/blob/master/HISTORY.md) has been updated, if appropriate

bug fix related to logits file check

---

GANDLF/training_loop.py
GANDLF/training_manager.py
HISTORY.md
README.md
testing/test_full.py

Fixes #181
- checkpoint loading added

Checkpoint loading added

---

GANDLF/compute/training_loop.py
GANDLF/logger.py

Fixes #N.A.
- syntax changes for a single if-else loop

Minor logging updates

---

GANDLF/metrics/__init__.py
GANDLF/metrics/generic.py
GANDLF/metrics/regression.py
GANDLF/parseConfig.py
HISTORY.md
samples/config_all_options.yaml
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml
testing/test_full.py

Fixes #197
- new metrics added

New metrics added

---

GANDLF/data/augmentation/README.md
GANDLF/data/augmentation/wrap_torchio.py
GANDLF/parseConfig.py
HISTORY.md
samples/config_all_options.yaml

Fixes #200 
- new functionality exposed for affine
- docs updated for augmentations

Affine augmentations enhancements

---

GANDLF/cli/preprocess_and_save.py
testing/test_full.py

Fixes #N.A.
- bugfix for csv writing after preprocessing
- reported by @karkadad

bugfix for csv writing

---

GANDLF/compute/forward_pass.py
GANDLF/models/densenet.py
GANDLF/models/seg_modules/get_num_classes.py
GANDLF/models/vgg.py

Fixes #204
- fix for regression nan
- includes #203

Regression nan fix

---

GANDLF/compute/forward_pass.py

Fixes #N.A.
- unique output folders for qualitative assessment of validation outputs

ensuring output dir always contains epoch info so that outputs are not overwritten

---

GANDLF/compute/forward_pass.py
GANDLF/models/densenet.py
GANDLF/models/uinc.py
GANDLF/models/unet.py
GANDLF/models/vgg.py
testing/test_full.py

Fixes #N.A.
- Divisibility check added
- test updated for assertion failure

Divisibility check added for unet/resunet/unic

---

GANDLF/utils/tensor.py
HISTORY.md

Fixes #209
- penalty calculation fixed
- new output for same example (in issue):
```
penalty_dict: {0: 0.006036875965002797, 1: 0.9939631240349976} 
weights_dict: {0: 0.9939631240349974,   1: 0.006036875965002573}
```
Values are slightly different because of the difference in how the data is split between training and validation.

209 penalty fix

---

GANDLF/compute/training_loop.py
GANDLF/parseConfig.py

Fixes #N.A.
- minor default change

Default for `"amp"` removed, because it is handled within `"model"`

---

GANDLF/compute/forward_pass.py
GANDLF/compute/step.py
GANDLF/compute/training_loop.py
GANDLF/data/ImagesFromDataFrame.py
GANDLF/losses/segmentation.py
GANDLF/parseConfig.py
GANDLF/utils/tensor.py

Fixes #212
- `one_hot` and related functionality fixed
- RGB check and fix for label has been added

Fixes for `one_hot` and `reverse_one_hot`

---

GANDLF/parseConfig.py

print statement updated

---

GANDLF/compute/inference_loop.py
GANDLF/compute/training_loop.py
GANDLF/data/ImagesFromDataFrame.py
GANDLF/models/fcn.py
GANDLF/models/light_unet.py
GANDLF/models/modelBase.py
GANDLF/models/seg_modules/IncDropout.py
GANDLF/models/seg_modules/UpsamplingModule.py
GANDLF/models/unet.py
GANDLF/optimizers/wrap_torch.py
testing/test_full.py

Fixes #N.A.
- fixing some issues on [codacy](https://app.codacy.com/gh/CBICA/GaNDLF/issues?categoryType=CodeStyle)
- making sure tests run with a single split, not multiple (which happens after training manager gets initialized)

fixing codacy issues

---

GANDLF/data/preprocessing/normalize_rgb.py

Fixes #N.A.
- simpler normalize functionality for rgb images

Simpler rgb normalize functionality

---

docs/usage.md
gandlf_collectStats
gandlf_constructCSV
gandlf_preprocess
gandlf_run

Fixes #N.A.
- CLI has been updated to make it cleaner

Updated cli

---

GANDLF/inference_manager.py

Fixes #N.A.
- single fold inference fixed

fixing single fold inference

---

HISTORY.md
docs/usage.md
gandlf_patchMiner

Fixes #247 
- OPM hash updated
- documentation added on how to use OPM

Updating OPM hash and fixing documentation

---

GANDLF/compute/inference_loop.py

Fixes #249
- 
- [ x] I have read the [`CONTRIBUTING`](https://github.com/CBICA/GaNDLF/blob/master/CONTRIBUTING.md) guide
- [x ] My PR is based from the [current GaNDLF master ](https://garygregory.wordpress.com/2016/11/10/how-to-catch-up-my-git-fork-to-master/)
- [ x] Function/class source code documentation added/updated
- [x ] Code has been [blacked](https://github.com/psf/black#usage) for style consistency
- [ x] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/CBICA/GaNDLF/blob/master/GANDLF/version.py)

Fix for the torch.load issue

---

.github/PULL_REQUEST_TEMPLATE.md
docs/setup.md

Fixes #N.A.
- added a comment in PR template
- updated installation docs

Update some docs

---

docs/setup.md

Update installation instruction for openslide

---

.github/ISSUE_TEMPLATE/---bug-report.md

Fixes #N.A.
- updated PR to give an example to get GaNDLF's version information from virtul environment

added an example of getting version of GaNDLF

---

GANDLF/version.py
HISTORY.md
samples/config_all_options.yaml
samples/config_classification.yaml
samples/config_regression.yaml
samples/config_segmentation_brats.yaml
samples/config_segmentation_histology.yaml
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml

updated version for development

---

GANDLF/utils/parameter_processing.py

Fixes #N.A.
- reported and fixed by JW

Fix for `get_final_layer` use in `GANDLF.utils`

---

GANDLF/parseConfig.py

Fixes #266
- Dict initialization fixed

updated initialization for dicts

---

setup.py

added `black` and `opencv-python` as an explicit requirements

---

GANDLF/models/densenet.py
HISTORY.md
testing/test_full.py

Fixes #273
- `DenseNet` now supports `InstanceNorm`

Added capability to use `InstanceNorm` in `DenseNet`

---

GANDLF/models/__init__.py
GANDLF/models/densenet.py
GANDLF/models/modelBase.py
GANDLF/models/vgg.py
GANDLF/utils/parameter_processing.py
HISTORY.md
samples/config_all_options.yaml
testing/test_full.py

Fixes #275
- `ModelBase` implementation updates to make all functions consistent
- `VGG` and `DenseNet` updated to used `ModelBase`
- Tests updated for `norm_type: none`

Updated implementations of `VGG` and `DenseNet` to use `ModelBase` for consistency

---

GANDLF/utils/modelio.py
HISTORY.md

Fixes #N.A.
- saved model now includes git hash

Added git hash to model save

---

GANDLF/utils/modelio.py

Fixes #N.A.
- put the git_hash request under a try-catch so that it doesn't fail if gandlf is installed from conda or tag

Update to how `git_hash` is saved

---

docs/extending.md
docs/faq.md

Documentation updated for new module structure

---

GANDLF/metrics/__init__.py
GANDLF/metrics/generic.py
GANDLF/metrics/regression.py
GANDLF/parseConfig.py
HISTORY.md
docs/faq.md
samples/config_all_options.yaml
testing/config_regression.yaml
testing/test_full.py

Fixes #286
- accuracy is now getting invoked from torchmetrics
- `parseConfig` is significantly simplified

Accuracy is now standardized from torchmetrics

---

.coveragerc
.github/workflows/python-test.yml
.gitmodules
GANDLF/anonymize/__init__.py
HISTORY.md
gandlf_anonymizer
pyproject.toml
samples/config_anonymizer.yaml
setup.py
testing/test_full.py

Fixes #290
- this handles dicom scans for now, extendable for path images

Added a `GANDLF.anonymize` module

---

.coveragerc
.github/workflows/python-test.yml
docs/usage.md
setup.py

Fixes #295
- `pip install -e .` performs `git submodule update` automatically
- minor rename of CI jobs

Git submodule update is now integrate in setup

---

.github/workflows/python-test.yml
GANDLF/parseConfig.py
setup.py

Fixes #N.A.
- fixing defaults for `colorjitter` properly
- using conda instead of mamba for tests because GH actions were taking longer to resolve mamba
- min python updated because numpy no longer has support for 3.6 for version 1.21 [[ref](https://numpy.org/devdocs/release/1.21.0-notes.html)]

Ensure `colorjitter` works with defaults

---

GANDLF/cli/preprocess_and_save.py
GANDLF/compute/inference_loop.py
GANDLF/compute/training_loop.py
GANDLF/data/ImagesFromDataFrame.py
GANDLF/schedulers/wrap_torch.py
GANDLF/utils/tensor.py
HISTORY.md
testing/test_full.py

Fixes #300
- added progress bars during queue construction and penalty loader loop

More progress bars for better feedback

---

docs/usage.md

Switch
`-i /path/to/trained/models \  # directory which contains testing and validation models`
to 
`-m /path/to/trained/models \  # directory which contains testing and validation models`

Update usage.md - plot final results

---

docs/extending.md

Fixes #N.A.
- documentation update

Added instructions for dependency management

---

GANDLF/cli/main_run.py

Fixes #309
- trying to make reset work in an easier way

Minor fix for `reset_prev` 

---

docs/usage.md

Fixes #N.A.
- links updated in documentation, no code change

added captk and fets links

---

docs/index.md
docs/usage.md

Fixes #N.A.
- defining discussions and email as separate bullet points
- added examples

Updates documentation based on SB's notes

---

GANDLF/cli/preprocess_and_save.py
gandlf_preprocess

Fixes #316
- using `applyaugs` as the cli parameter, a user can save preprocessed files with augmentation

Added ability to save preprocessed files with data augmentation

---

GANDLF/models/__init__.py
GANDLF/models/resnet.py
testing/test_full.py

- create resnet model
- add resnet models to __init__.py
- test cases

Added ResNet with multiple configurations

---

GANDLF/compute/training_loop.py
GANDLF/data/ImagesFromDataFrame.py
GANDLF/data/preprocessing/__init__.py
GANDLF/data/preprocessing/resample_minimum.py
HISTORY.md
samples/config_all_options.yaml
testing/test_full.py

Fixes #324
- this can be used to force all images to have a minimum resolution before getting processed
- typos fixed in test
- best epoch information is now getting displayed

`Resample_Min` added to ensure a baseline resolution for all images getting processed

---

GANDLF/cli/preprocess_and_save.py
GANDLF/data/ImagesFromDataFrame.py
GANDLF/parseConfig.py

Fixes #N.A.
- Duplicate of #327 
- Hash updates to OPM

Adding EfficientNet, ensuring cropping zero planes are applied for preprocessing

---

GANDLF/metrics/__init__.py

Typo fixed for `hd95`

---

GANDLF/cli/preprocess_and_save.py
GANDLF/compute/training_loop.py
GANDLF/data/ImagesFromDataFrame.py
GANDLF/parseConfig.py
GANDLF/utils/__init__.py
GANDLF/utils/imaging.py
HISTORY.md
samples/config_all_options.yaml
testing/test_full.py

Fixes #336
- added resize image and patch separately
- Checks updated for resample, so that if both resize and resample are selected, only resample happens

Adding `resize_image` as a separate option as compared to `resize_patch`

---

GANDLF/data/ImagesFromDataFrame.py
GANDLF/utils/imaging.py

Fixes #339
- sanity check is now softer to allow for _slightly_ misaligned headers

Sanity checking is now softer with a threshold

---

GANDLF/cli/main_run.py
GANDLF/training_manager.py
HISTORY.md
docs/faq.md
docs/usage.md
gandlf_run
testing/test_full.py

Fixes #343
- added functionality to resume with parameter updates (this only uses the previously saved model information and nothing else)
- added function to resume without parameter updates (this was the "non reset" option before)
- documentation (usage and faq) updated
- bunch of updated comments
- streamlined the tests

Added ability to resume with and without updating parameters and/or data

---

GANDLF/parseConfig.py
GANDLF/utils/tensor.py
HISTORY.md
testing/test_full.py

Fixes #341 
- updating reverse one-hot logic

Reverse one-hot logic is now updated to output unique labels

---

GANDLF/compute/training_loop.py
GANDLF/models/Readme.md

Fixes #345
- readme update to include links 
- print for best epoch updated

Links added for current networks

---

.github/workflows/docker-image.yml

Fixes #N/A
- Adds upload to GitHub Packages (in addition to the existing Docker Hub upload)
- Applies metadata labels to make containers OCI compliant
- Small changes to the Docker CI workflow (automatic tag names, placeholder testing step)
As with last time, this PR won't be able to access secrets to authorize the Docker Hub push (or the GitHub Packages push either, which uses GitHub credentials). Should be merged to the docker_ci branch first, then a PR opened to master for the checks to work.
If the ghcr.io upload throws a permission error, this means the "current user" can't publish packages on the CBICA organization. Current user is probably tied to the person whose action triggered the workflow (probably @sarthakpati if he opens a second PR targeting master).

Add GitHub Packages upload step, refine Docker CI further

---

.github/workflows/docker-image.yml
Dockerfile-CPU
Dockerfile-CUDA10.2
Dockerfile-CUDA11.3
Dockerfile-ROCm
HISTORY.md
README.md

Fixes #N.A.
- see title
- added status badge

Added Docker Image builds 

---

GANDLF/compute/forward_pass.py
GANDLF/compute/step.py
GANDLF/inference_manager.py
GANDLF/utils/__init__.py
GANDLF/utils/generic.py
HISTORY.md
testing/test_full.py

Fixes #360
- added logic to not require ground truth during inference

Enabling inference without having access to the ground truth

---

GANDLF/parseConfig.py

Fixes #N.A.
- parsing issue with balanced accuracy; reported by @ujjwalbaid0408

Fixed issue with `balanced_accuracy` parsing

---

.github/workflows/python-test.yml
Dockerfile-CPU
Dockerfile-CUDA10.2
Dockerfile-CUDA11.3
GANDLF/utils/modelio.py
docs/setup.md
setup.py

Fixes #N.A.
- requirement set for LTS
- setup updated
- updated CI runners

Hard requirement of PyTorch to LTS

---

.github/workflows/docker-image.yml
Dockerfile-CPU
Dockerfile-CUDA10.2
Dockerfile-CUDA11.3
Dockerfile-ROCm

Merging changes into Sarthak's PR for ease.

Fix Docker CI on PRs again (meta information missing causing a rebuild -> out of space)

---

.github/workflows/docker-image.yml
Dockerfile-CPU
Dockerfile-CUDA10.2
Dockerfile-CUDA11.3
Dockerfile-ROCm

Fixing docker builds

---

GANDLF/compute/inference_loop.py
GANDLF/compute/loss_and_metric.py
GANDLF/data/ImagesFromDataFrame.py
GANDLF/data/inference_dataloader_histopath.py
GANDLF/data/preprocessing/__init__.py
GANDLF/inference_manager.py
GANDLF/parseConfig.py
GANDLF/utils/write_parse.py
HISTORY.md
gandlf_constructCSV
testing/test_full.py

Fixes #N.A.
- customized inference for histology classification
- logic updates for constructing preprocessing transforms

Custom inference loop added for histo classification

---

samples/config_all_options.yaml

Fixes #N.A.
- added comment in all options config

added a comment about padding options

---

samples/config_all_options.yaml

Fixes #N.A.
- minor update in comment

updated config comment for `num_channels`

---

GANDLF/schedulers/wrap_torch.py

Logic fixed for step scheduler

---

docs/usage.md

Fixes #N.A.
- documentation update

Added note for classification/regression tasks

---

GANDLF/data/preprocessing/__init__.py
GANDLF/data/preprocessing/rgba2rgb.py
HISTORY.md
samples/config_all_options.yaml
testing/test_full.py

Fixes #383
- added preprocessing code for RGBA to RGB conversion using PIL
- variable renamed in preprocessing submodule for clarity

Added RGBA to RGB conversion in preprocessing

---

GANDLF/schedulers/__init__.py

- added a key for `exp` scheduler

Added a key for `exp` scheduler

---

docs/extending.md
docs/faq.md
docs/usage.md

Fixes #N.A.
- main section identifier removed
- another faq point added

Documentation updates

---

GANDLF/compute/forward_pass.py
GANDLF/parseConfig.py
HISTORY.md
samples/config_all_options.yaml
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml

Fixes #391
- defaults to `'crop'`
- [x ] [History](https://github.com/CBICA/GaNDLF/blob/master/HISTORY.md) has been updated, if appropriate

Add option to strategize the final aggregation for segmentation

---

GANDLF/compute/forward_pass.py
GANDLF/compute/training_loop.py
GANDLF/metrics/segmentation.py

Fixes #N.A.
- per label metrics are now display as expected

Fixing per-label metrics display

---

GANDLF/data/preprocessing/__init__.py
GANDLF/data/preprocessing/rgb_conversion.py
HISTORY.md
testing/test_full.py

Fixes #N.A.
- this would be very useful in addition to have rgba to rgb

Added RGB to RGBA conversion for preprocessing

---

GANDLF/compute/forward_pass.py
GANDLF/compute/step.py
GANDLF/compute/training_loop.py
GANDLF/models/deep_unet.py
GANDLF/models/light_unet.py
GANDLF/models/light_unet_multilayer.py
GANDLF/models/modelBase.py
GANDLF/models/seg_modules/out_conv.py
GANDLF/models/unet.py
GANDLF/models/unet_multilayer.py
GANDLF/models/unetr.py
HISTORY.md
samples/config_all_options.yaml
setup.py
testing/config_segmentation.yaml
testing/test_full.py

Fixes #N.A.
- sigmoid multiplier has been added for `out_conv` for UNet models 
- making some redundant print statements come under `verbose` flag

Added sigmoid multiplier for UNet model output

---

docs/setup.md

Documentation update for installation

---

GANDLF/compute/forward_pass.py
GANDLF/parseConfig.py
GANDLF/utils/tensor.py
samples/config_all_options.yaml
setup.py
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml
testing/test_full.py

Fixes #N.A.
- `patch_overlap` option added for inference, defaults to `0`
- `patch_overlap` and `grid_aggregator_overlap` have been put under `inference_mechanism` key
- includes #404

More inference mode options added 

---

GANDLF/models/__init__.py
GANDLF/models/modelBase.py
GANDLF/utils/modelbase.py
GANDLF/utils/parameter_processing.py

circular import issue.
Fixes #406 
- move functionality for getting base model final layer so as to not cause circular import

moving get_final_layer method functionality to GANDLF.utils to avoid

---

GANDLF/compute/inference_loop.py
GANDLF/compute/training_loop.py

Fixes #N.A.
- no need to send model to device again

Fixes to model getting sent to device twice

---

GANDLF/compute/forward_pass.py
GANDLF/compute/inference_loop.py
GANDLF/compute/step.py
GANDLF/utils/modelio.py
docs/setup.md

Upgrade to OpenVINO 2022.1

---

GANDLF/compute/inference_loop.py

Fixes #N.A.
- model is now in proper device

Model device location fixed for inference

---

.github/workflows/python-test.yml
Dockerfile-CPU
Dockerfile-CUDA10.2
Dockerfile-CUDA11.3
Dockerfile-ROCm

Fixes #N.A.
- updated OV installation for automated builds (docker and CI tests) after #410
- this will not affect anything **till** a new version of OV is released, at which point stuff might break

Updated OpenVINO installation for CI

---

GANDLF/compute/generic.py
GANDLF/data/__init__.py

Fixes #N.A.
- no need to recreate a queue for populating headers from validation data - this does not create a lot of issue during unit testing, but for fully fleshed out training, it can be a time sink

Reducing dataframe iteration

---

docs/setup.md

Fixes #N.A.
- documentation update

Documentation update to use pip instead of conda, per our CI

---

GANDLF/cli/main_run.py

Fixes #N.A.
- previously, if train/val split was provided, it was try training again

Providing train/val split should not result in another training 

---

GANDLF/compute/step.py

Fixes #N.A.
- Fixing typo in torch.cuda.memory_summary()

Fix typo torch summary

---

GANDLF/models/modelBase.py

Fixes #428
- ensure user knows that only 2D or 3D computations are supported

Checking dimensionality of computations and raising run-time error

---

GANDLF/compute/forward_pass.py
GANDLF/compute/inference_loop.py
GANDLF/data/inference_dataloader_histopath.py
GANDLF/utils/generic.py
gandlf_run

Fixes #N.A.
- Fixes patches pulled from out of WSI

Histology inference logic updated

---

GANDLF/compute/inference_loop.py
GANDLF/utils/parameter_processing.py
docs/usage.md

Fixes #N.A.
- reduced number of lines of code for histo-specific inference
- redundant print removed
- hyperlinks updated in documentation

Simplified logic for histology inference

---

GANDLF/version.py

Fixes #N.A.
- version update for tagging

version update for tagging

---

GANDLF/compute/inference_loop.py
GANDLF/data/inference_dataloader_histopath.py
GANDLF/models/imagenet_vgg.py
GANDLF/parseConfig.py
HISTORY.md
testing/test_full.py

Fixes #454
- `stride_size` is now getting handled within the histology dataloader
- added a case for `patch_size` where one can pass a single int/float number

Fixing the `stride_size` check for histology inference

---

GANDLF/compute/inference_loop.py
GANDLF/data/__init__.py

Fixes #N.A.
- When testing data is used, some params keys are not populated, which could result in weird downstream errors 
- This PR puts a conditional check for the main such param key and then populates it correctly

Ensuring params are populated correctly even if only testing data is invoked

---

GANDLF/compute/inference_loop.py
GANDLF/data/inference_dataloader_histopath.py

Fixes #459
- using higher dtype for stride size so that it can be parsed correctly
- removed some redundant code
- code coverage reduced because of reduction in lines of code

Update data type for stride size

---

.github/workflows/python-test.yml
setup.py
testing/test_full.py

Fixes #476
- added testing for exception for large histology images

Added exception testing for histology classification

---

.github/workflows/python-test.yml

- Add path-ignore filtering to the test workflow so that it doesn't run only on doc changes. Keeping it minimal because other files (e.g. MANIFEST.in) could actually end up affecting the build.
- Everything else still runs.

Update test workflow with file path filtering

---

GANDLF/compute/forward_pass.py
GANDLF/data/post_process/morphology.py
GANDLF/metrics/__init__.py
GANDLF/metrics/regression.py
GANDLF/utils/__init__.py
GANDLF/utils/generic.py
GANDLF/utils/tensor.py
HISTORY.md
docs/extending.md
samples/config_all_options.yaml
testing/config_classification.yaml
testing/test_full.py

Fixes #485
- new metric has been added
- documentation updates
- typo fix
- includes #483

New metric added to calculated per-class accuracy

---

GANDLF/data/post_process/__init__.py
GANDLF/data/post_process/morphology.py
HISTORY.md
gandlf_collectStats
testing/test_full.py

Adds connected component analysis

Adding Largest connected component analysis as a post-processing step

---

GANDLF/metrics/regression.py

Fixes #497
- logic fixed to allow multi-batch input

Fixes multi-batch issue for `per_label_accuracy`

---

GANDLF/compute/forward_pass.py
GANDLF/compute/step.py
GANDLF/compute/training_loop.py
GANDLF/metrics/__init__.py
GANDLF/metrics/classification.py
GANDLF/metrics/regression.py
GANDLF/utils/__init__.py
GANDLF/utils/tensor.py
HISTORY.md
testing/config_classification.yaml

Fixes #N.A.
- storing predictions and ground truths for training and validation, and then running torchmetrics functions on it to get overall metrics
- single function to get the ground truth array and baseline prediction tensor to reduce code duplication
- unified api for `step` function
- new submodule to calculate `classification` metrics
- renamed `per_label_accuracy` to `per_label_one_hot_accuracy` for clarity

Included classification-specific metrics using overall predictions and ground truths

---

.github/workflows/python-test.yml
Dockerfile-CPU
Dockerfile-CUDA10.2
Dockerfile-CUDA11.3
Dockerfile-ROCm
GANDLF/models/imagenet_unet.py
GANDLF/models/imagenet_vgg.py
GANDLF/models/light_unet_multilayer.py
GANDLF/models/transunet.py
GANDLF/models/unet.py
GANDLF/models/unet_multilayer.py
GANDLF/training_manager.py
GANDLF/utils/generic.py
HISTORY.md
docs/setup.md
samples/config_all_options.yaml
setup.py
testing/test_full.py

Fixes #441
- encoders pretrained on imagenet with segmentation and classification heads (accepted in brainless 22)
- allow `imagenet_vgg` to be randomly initialized, with dimensionality check
- allow previous unets (standard 4-layer, multilayer and light multilayer) to be converted
- save validation data split into csv
- torch version requirement updated
- includes #443
- to be reviewed after #502

Added ImageNet-trained encoders with segmentation and classification heads

---

GANDLF/compute/forward_pass.py
GANDLF/compute/training_loop.py
GANDLF/metrics/__init__.py
GANDLF/metrics/classification.py
GANDLF/metrics/regression.py
GANDLF/utils/__init__.py
GANDLF/utils/tensor.py

Fixes #506
- overhaul of the way `overall_stats` are calculated for classification to include regression workloads
- hopefully will make proposals in #505 easier to accomplish

Adding cohort-level metrics for regression

---

docs/setup.md
docs/usage.md

Fixes #533
- Adds usage and setup info for Docker container versions of GaNDLF (as well as some very basic MLCube usage info).
- [xxxxx] [Usage documentation](https://github.com/mlcommons/GaNDLF/blob/master/docs) has been updated, if appropriate

Add docker docs

---

GANDLF/cli/main_run.py
GANDLF/compute/inference_loop.py
GANDLF/inference_manager.py
gandlf_run
testing/test_full.py

Fixes #556
- inference API is now updated to take care of potential access issues

Separate `modelDir` and `outputDir` parameters for inference to cohesiveness

---

GANDLF/compute/loss_and_metric.py
GANDLF/compute/training_loop.py

Fixes #555
- the headers from `overall_stats` are now populated correctly
- done in a way that any future addition/removal of overall_metrics will be automatically included

The logs now include metric headers from `overall_stats`

---

GANDLF/parseConfig.py

Fixes an issue wherein parseConfig is failing for noise augmentation because an if check is missing for the associated mean.
- adds the if check to be consistent with other augmentations in parseConfig.

Fix parseConfig separately from my other PR

---

.github/workflows/main.yml

- Adds PyPI-based package creation

Create GitHub Action to push to PyPI automatically upon release creation

---

README.md

Repository badges have been updated

---

.github/workflows/check_pull_request_title.yml

old version prohibited first word to finish with `s` char, that is quite a weird
`(?<!s)` means `there should not be an "s" char`, that's quite dumb. Removing this restriction

PR title regex fix

---

GANDLF/config_manager.py
docs/faq.md

[pkg_resources ](https://setuptools.pypa.io/en/latest/pkg_resources.html) is deprecated. Using it breaks gandlf now: while extracting gandlf version, it builds a whole tree of dependencies and fails as [`torchio` requires `typer[all]`](https://github.com/fepegar/torchio/blob/main/setup.cfg#L52), while [modern ](https://pypi.org/project/typer/0.12.1/)typer==0.12.0+ doesn't have `all` option anymore (compare to [0.11.1, "Installation" section](https://pypi.org/project/typer/0.11.1/)). Though the issue itself is very minor, `pkg_resources` treat it as critical and fails.
The best solution is just to replace pkg_resources with more modern tools
- replace `pkg_resources` with `importlib.metadata` to extract gandlf version

Deprecated pkg resources

---

GANDLF/metrics/classification.py

Fixes #N.A.
- removing `auroc` from computation until #817 is resolved

Commenting out auroc

---

GANDLF/data/augmentation/blur_enhanced.py
GANDLF/data/augmentation/noise_enhanced.py

Fixes #859
- calling `.float()` before `torch.std` for noise and blur enhanced

Ensure a float tensor is passed for augmentations 

---

GANDLF/inference_manager.py

Fixes #862 
- Ensured that n_folds is not used to trigger logit saving

Refactor inference manager code to save correct files

---

.github/workflows/black.yml

Update black action with specific version

---

GANDLF/entrypoints/config_generator.py
GANDLF/entrypoints/verify_install.py

Fixes #N.A.
- extra `"` removed

Minor typos removed

---

.devcontainer/onCreateCommand.sh
.github/workflows/black.yml
.github/workflows/main.yml
.github/workflows/mlcube-test.yml
.github/workflows/openfl-test.yml
.github/workflows/publish-nightly.yml
.github/workflows/python-test.yml
Dockerfile-CPU
Dockerfile-CUDA11.8
Dockerfile-CUDA12.1
Dockerfile-ROCm

Fixes #N.A.
- ensure pip version for master as well #887

Fixed pip version for CI tests

---

GANDLF/data/preprocessing/__init__.py
testing/test_full.py

Fixes #907
- adjusted parameter handling during Rescaler instantiation so that now they indeed take an effect when the object is called
- adjusted unit tests - as the new method previously did not care about input parameters, it so happened that default values were able to pass all the tests. However now, when we pass different [min, max] pixel range into `in_min_max` parameter, it affects the result scaling of the given tensor, even despite `out_min_max` being set to given threshodl. Given that, tests are updated and now use the real [min, max] range of the random tensor
- [] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/mlcommons/GaNDLF/blob/master/GANDLF/version.py).
- [] If adding a git submodule, add to list of exceptions for black …

Adding proper parameter usage in the class constructor

---

.github/workflows/publish-nightly.yml
.github/workflows/python-test.yml

Updated version check for nightly builds

---

.github/workflows/publish-nightly.yml

Ensure all build commands are in single step

---

GANDLF/utils/data_splitter.py

- Just changed the cross validation message to something clearer and less blunt

Changed warning message

---

GANDLF/optimizers/__init__.py
GANDLF/optimizers/ademamix.py
GANDLF/optimizers/wrap_monai.py
GANDLF/optimizers/wrap_torch.py

Fixes #935
- added a the new ademamix optimizer

Added the ademamix optimizer

---

docs/index.md
docs/itcr_connectivity.md
mkdocs.yml

Fixes #937
- added dedicated section for ITCR connectivity map

Added itcr connectivity map

---

docs/faq.md
docs/migration_guide.md
mkdocs.yml

Fixes #843
- added a dedicated migration guide
- updated faq

Added migration guide

---

setup.py

Fixes #872
- Update the requests to 2.32.2.

Update requests version

---

GANDLF/version.py
samples/config_all_options.yaml
samples/config_classification.yaml
samples/config_getting_started_classification_histo2d.yaml
samples/config_getting_started_classification_rad3d.yaml
samples/config_getting_started_regression_histo2d.yaml
samples/config_getting_started_regression_rad3d.yaml
samples/config_getting_started_segmentation_histo2d.yaml
samples/config_getting_started_segmentation_rad3d.yaml
samples/config_regression.yaml
samples/config_segmentation_brats.yaml
samples/config_segmentation_histology.yaml
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml
tutorials/classification_medmnist_notebook/config.yaml

Version updated for tagging

---

.github/workflows/python-test.yml

Upload code coverage only from master

---

GANDLF/version.py
samples/config_all_options.yaml
samples/config_classification.yaml
samples/config_getting_started_classification_histo2d.yaml
samples/config_getting_started_classification_rad3d.yaml
samples/config_getting_started_regression_histo2d.yaml
samples/config_getting_started_regression_rad3d.yaml
samples/config_getting_started_segmentation_histo2d.yaml
samples/config_getting_started_segmentation_rad3d.yaml
samples/config_regression.yaml
samples/config_segmentation_brats.yaml
samples/config_segmentation_histology.yaml
testing/config_classification.yaml
testing/config_regression.yaml
testing/config_segmentation.yaml
tutorials/classification_medmnist_notebook/config.yaml

Fixes #N.A.
- new dependency added (openslide) and hence tagging before another dependency gets updated

Getting ready to tag new version with update dependencies

---

docs/faq.md

Fixes #N.A.
- Ensure that there is an FAQ point on how the version mismatch error can be addressed.

Added a faq point for the version mismatch

---

GANDLF/utils/gandlf_logging.py

Fixes #963 
- The logfile is saved in the tmp dir, but it causes an error.
- So, the logfile is saved in the $(home) dir

Change the default logfile 

---

.devcontainer/onCreateCommand.sh
.devcontainer/postCreateCommand.sh
.github/workflows/dependencies/action.yml
Dockerfile-CPU
Dockerfile-CUDA11.8
Dockerfile-CUDA12.1
Dockerfile-ROCm
docs/setup.md
setup.py

Fixes #N.A.
- slightly related to #968
- pytorch version updated

Updated PyTorch to newer version 

---

.devcontainer/onCreateCommand.sh
.devcontainer/postCreateCommand.sh
.github/workflows/dependencies/action.yml
Dockerfile-CPU
Dockerfile-CUDA11.8
Dockerfile-CUDA12.1
Dockerfile-ROCm
docs/setup.md
setup.py

Fixes #N.A.
- ensuring that we are meeting the min version of pytorch needed for #968

Update PyTorch to previous stable 

---

.github/workflows/codeql-analysis.yml
.github/workflows/ossar-analysis.yml
.github/workflows/spellchecker.yml

Fixes #978
- update the version of the ossar analysis action
- update the version of the codeql analysis action

Update versions for ossar and codeql actions

---

.github/workflows/ossar-analysis.yml

Update cron schedule for ossar

---

setup.py

Fixes #993 
Update segmentation-models-pytorch version
-

Update dependency version

---

.github/workflows/main.yml
.github/workflows/publish-nightly.yml

- updated version for the action `pypa/gh-action-pypi-publish` because nightly pushes were failing

Updated version for action

---

.github/workflows/python-install-check.yml

Fixes #1005
- added multi-platform install check

More robust CI

---

docs/usage.md

Usage document formatting updates

---

.spelling/.spelling/expect.txt
GANDLF/cli/generate_metrics.py
GANDLF/metrics/panoptica_config_brats.yaml
GANDLF/utils/__init__.py
GANDLF/utils/imaging.py

Fixes #1010
- added dedicated sanity check for images
- ensure only 3D arrays are going to panoptica

Added sanity check for metrics

---

GANDLF/metrics/segmentation_panoptica.py

Fixes #N.A.
- custom panoptica config full support

Panoptica updated with better logic

---

samples/config_segmentation_metrics_brats_concise.yaml
samples/config_segmentation_metrics_brats_default.yaml

- The docs site section on [Special cases](https://docs.mlcommons.org/GaNDLF/usage/#special-cases) references the `panoptica_config` dictionary, however the provided sample files uses `panoptica`, which leads to unexpected results when running GaNDLF. This PR updates the sample config files to correctly use `panoptica_config`, ensuring the custom configurations are applied instead of the default values.

Fix brats config samples

---

.spelling/.spelling/expect.txt
GANDLF/configuration/scheduler_config.py
GANDLF/schedulers/__init__.py
GANDLF/schedulers/wrap_torch.py

Fixes #N.A.
- added cosine annealing LR and differentiated it with cosine annealing warm restarts

Added new scheduler

---

.github/workflows/python-test.yml
docs/customize.md

Fixes #953
- updated note about classification and regression metrics

Updated documentation about metrics

---

.github/workflows/docker-image.yml

Fixes #N.A.
- adds a specific `latest` tag for the docker images
- related to #1034

Add a new tag for the docker images being built

---

.github/workflows/docker-image.yml

Fixes #N.A.
- trying to build a simple `latest` docker image

Added a simple latest tag
